### PR TITLE
Fix bwa mem2

### PR DESCRIPTION
**Pull request by shawnpg**
Update hic_qc to support bwa-mem2 in response to a user-reported error. Also fix a bug when samblaster was not used, which was uncovered during the process of making this fix.

### CODE REVIEW

**Comment by bnelsj** [comment]
Code looks good, but a test or two here would be great.

**Comment by bnelsj** [comment]
Do we want the PR to target dev instead of master?

**Review by bnelsj — CHANGES_REQUESTED** [review]
Code looks fine, but PR should target dev and tests should be added.

**Comment by shawnpg** [comment]
Thanks! Unit tests added and PR rebased to dev

**Review by bnelsj — APPROVED** [review]
Looks good!

**Pull request merged**
